[[mods]]
name = "Carpet"
slug = "carpet"
settings_classes = ["carpet.CarpetSettings"]

[mods.versions."1.14"]
minecraft_version = "1.14.4"
printer_version = "v1"
source = { host = "Modrinth", version = "1.3.7" }

[mods.versions."1.15"]
minecraft_version = "1.15.2"
printer_version = "v1"
source = { host = "Modrinth", version = "1.4.8" }

[mods.versions."1.16"]
minecraft_version = "1.16.5"
printer_version = "v1"
source = { host = "Modrinth", version = "1.4.44" }

[mods.versions."1.17"]
minecraft_version = "1.17.1"
printer_version = "v1"
source = { host = "Modrinth", version = "1.4.57" }

[mods.versions."1.18"]
minecraft_version = "1.18.2"
printer_version = "v1"
source = { host = "Modrinth", version = "1.4.69" }

[mods.versions."1.19"]
minecraft_version = "1.19.4"
printer_version = "v2"
source = { host = "Modrinth", version = "1.4.101" }

[mods.versions."1.20"]
minecraft_version = "1.20.1"
printer_version = "v2"
source = { host = "Modrinth", version = "1.4.112" }

[[mods]]
name = "Carpet Extra"
slug = "carpet-extra"
entrypoint = "carpetextra.CarpetExtraServer"
settings_classes = ["carpetextra.CarpetExtraSettings"]

[mods.versions."1.14"]
minecraft_version = "1.14.4"
printer_version = "v1"
entrypoint = ""
dependencies = ["maven.modrinth:carpet:1.3.7"]
source = { host = "Modrinth", version = "1.3.5-1.14.4" }

[mods.versions."1.15"]
minecraft_version = "1.15.2"
printer_version = "v1"
entrypoint = ""
dependencies = ["maven.modrinth:carpet:1.4.8"]
source = { host = "Modrinth", version = "1.4.0-1.15.2" }

[mods.versions."1.16"]
minecraft_version = "1.16.5"
printer_version = "v1"
dependencies = ["maven.modrinth:carpet:1.4.44"]
source = { host = "Modrinth", version = "1.4.43-1.16.5" }

[mods.versions."1.17"]
minecraft_version = "1.17.1"
printer_version = "v1"
dependencies = ["maven.modrinth:carpet:1.4.57"]
source = { host = "Modrinth", version = "1.4.57-1.17.1" }

[mods.versions."1.18"]
minecraft_version = "1.18.2"
printer_version = "v1"
dependencies = ["maven.modrinth:carpet:1.4.69"]
source = { host = "Modrinth", version = "1.4.72-1.18.2" }

[mods.versions."1.19"]
minecraft_version = "1.19.4"
printer_version = "v3"
dependencies = ["maven.modrinth:carpet:1.4.101"]
source = { host = "Modrinth", version = "1.4.100-1.19.4" }

[mods.versions."1.20"]
minecraft_version = "1.20.1"
printer_version = "v3"
dependencies = ["maven.modrinth:carpet:1.4.112"]
source = { host = "Modrinth", version = "1.4.115" }

[[mods]]
name = "Rug"
slug = "rug"
project_id = 449938
entrypoint = "de.rubixdev.rug.RugServer"
settings_classes = ["de.rubixdev.rug.RugSettings"]

[mods.versions."1.16"]
minecraft_version = "1.16.5"
printer_version = "v1"
dependencies = ["maven.modrinth:carpet:1.4.44"]
source = { host = "CurseForge", file_id = 3387640 }

[mods.versions."1.17"]
minecraft_version = "1.17.1"
printer_version = "v1"
dependencies = ["maven.modrinth:carpet:1.4.57"]
source = { host = "CurseForge", file_id = 3545382 }

[mods.versions."1.18"]
minecraft_version = "1.18.2"
printer_version = "v1"
dependencies = ["maven.modrinth:carpet:1.4.69"]
source = { host = "CurseForge", file_id = 3687028 }

[mods.versions."1.19"]
minecraft_version = "1.19.4"
printer_version = "v3"
dependencies = ["maven.modrinth:carpet:1.4.101"]
source = { host = "Modrinth", version = "1.4.1+1.19.4" }

[mods.versions."1.20"]
minecraft_version = "1.20.1"
printer_version = "v3"
dependencies = ["maven.modrinth:carpet:1.4.112"]
source = { host = "Modrinth", version = "1.4.4+1.20.1" }

[[mods]]
name = "Minitweaks"
slug = "minitweaks"
repo = "manyrandomthings/minitweaks"
entrypoint = "minitweaks.MiniTweaks"
settings_manager = "minitweaks.MiniTweaksCarpetExtension.settingsManager"
settings_classes = ["minitweaks.MiniTweaksSettings"]

[mods.versions."1.15"]
minecraft_version = "1.15.2"
printer_version = "v1"
entrypoint = ""
settings_manager = ""
settings_classes = ["mini_tweaks.MiniTweaksSettings"]
dependencies = ["maven.modrinth:carpet:1.4.8"]
source = { host = "GitHub", tag = "1.0.1", artifact = "mini-tweaks-1.0.1-1.15.2.jar" }

[mods.versions."1.16"]
minecraft_version = "1.16.5"
printer_version = "v1"
settings_manager = "minitweaks.MiniTweaks.settingsManager"
dependencies = ["maven.modrinth:carpet:1.4.44"]
source = { host = "Modrinth", version = "1.0.16" }

[mods.versions."1.17"]
minecraft_version = "1.17.1"
printer_version = "v1"
settings_manager = "minitweaks.MiniTweaks.settingsManager"
dependencies = ["maven.modrinth:carpet:1.4.57"]
source = { host = "Modrinth", version = "1.1.5" }

[mods.versions."1.18"]
minecraft_version = "1.18.2"
printer_version = "v1"
settings_manager = "minitweaks.MiniTweaks.settingsManager"
dependencies = ["maven.modrinth:carpet:1.4.69"]
source = { host = "Modrinth", version = "1.2.3" }

[mods.versions."1.19"]
minecraft_version = "1.19.4"
printer_version = "v3"
dependencies = ["maven.modrinth:carpet:1.4.101"]
source = { host = "Modrinth", version = "1.3.6" }

[mods.versions."1.20"]
minecraft_version = "1.20.1"
printer_version = "v3"
dependencies = ["maven.modrinth:carpet:1.4.112"]
source = { host = "Modrinth", version = "1.4.0" }

[[mods]]
name = "Carpet-Fixes"
slug = "carpet-fixes"
repo = "fxmorin/carpet-fixes"
entrypoint = "carpetfixes.CarpetFixesServer"
settings_manager = "carpetfixes.CarpetFixesServer.carpetFixesSettingsManager"
settings_classes = ["carpetfixes.CFSettings"]

[mods.versions."1.16"]
minecraft_version = "1.16.5"
printer_version = "v1"
settings_manager = ""
settings_classes = ["carpetfixes.CarpetFixesSettings"]
dependencies = ["maven.modrinth:carpet:1.4.44"]
source = { host = "GitHub", tag = "v0.0.6", artifact = "carpetfixes-1.16.5-0.0.6.jar" }

[mods.versions."1.17"]
minecraft_version = "1.17.1"
printer_version = "v1"
settings_classes = ["carpetfixes.CarpetFixesSettings"]
dependencies = ["maven.modrinth:carpet:1.4.57"]
source = { host = "Modrinth", version = "v1.3.0" }

[mods.versions."1.18"]
minecraft_version = "1.18.2"
printer_version = "v1"
dependencies = [
    "maven.modrinth:carpet:1.4.69",
    "com.github.Fallen-Breath:conditional-mixin:v0.3.1",
    "com.github.LlamaLad7:MixinExtras:0.0.6",
]
source = { host = "Modrinth", version = "v1.7.11" }

[mods.versions."1.19"]
minecraft_version = "1.19.4"
printer_version = "v3"
dependencies = [
    "maven.modrinth:carpet:1.4.101",
    "com.github.Fallen-Breath:conditional-mixin:v0.3.1",
    "com.github.LlamaLad7:MixinExtras:0.0.6",
]
source = { host = "Modrinth", version = "v1.14.1" }

[mods.versions."1.20"]
minecraft_version = "1.20.1"
printer_version = "v3"
dependencies = [
    "maven.modrinth:carpet:1.4.112",
    "com.github.Fallen-Breath:conditional-mixin:v0.3.1",
    "com.github.llamalad7.mixinextras:mixinextras-fabric:0.2.0-beta.9",
]
source = { host = "Modrinth", version = "v1.16.1" }

[[mods]]
name = "Carpet AutoCraftingTable"
slug = "carpet-autocraftingtable"
repo = "gnembon/carpet-autoCraftingTable"
settings_classes = ["carpet_autocraftingtable.AutoCraftingTableSettings"]

[mods.versions."1.14"]
minecraft_version = "1.14.4"
printer_version = "v1"
dependencies = ["maven.modrinth:carpet:1.3.7"]
source = { host = "GitHub", tag = "v1.0", artifact = "carpet-autocraftingtable-1.14.4-1.3.0.jar" }

[mods.versions."1.15"]
minecraft_version = "1.15.2"
printer_version = "v1"
dependencies = ["maven.modrinth:carpet:1.4.8"]
source = { host = "GitHub", tag = "v1.0", artifact = "carpet-autocraftingtable-1.15.2-1.3.11.jar" }

[mods.versions."1.16"]
minecraft_version = "1.16.5"
printer_version = "v1"
dependencies = ["maven.modrinth:carpet:1.4.44"]
source = { host = "GitHub", tag = "v1.4", artifact = "carpet-autocraftingtable-1.16.4-1.4.17_build2.jar" }

[mods.versions."1.17"]
minecraft_version = "1.17.1"
printer_version = "v1"
dependencies = ["maven.modrinth:carpet:1.4.57"]
source = { host = "GitHub", tag = "1.4.43", artifact = "carpet-autocraftingtable-1.17.1-1.4.43.jar" }

[mods.versions."1.18"]
minecraft_version = "1.18.2"
printer_version = "v1"
dependencies = ["maven.modrinth:carpet:1.4.69"]
source = { host = "GitHub", tag = "1.4.56", artifact = "carpet-autocraftingtable-1.18-1.4.56.jar" }

[mods.versions."1.19"]
minecraft_version = "1.19.4"
printer_version = "v3"
dependencies = ["maven.modrinth:carpet:1.4.101"]
source = { host = "GitHub", tag = "1.4.100", artifact = "carpet-autocraftingtable-1.19.4-1.4.100.jar" }

[mods.versions."1.20"]
minecraft_version = "1.20.1"
printer_version = "v3"
dependencies = ["maven.modrinth:carpet:1.4.112"]
source = { host = "GitHub", tag = "1.4.112", artifact = "carpet-autocraftingtable-1.20-1.4.112.jar" }

[[mods]]
name = "Carpet Sky Additions"
slug = "carpet-sky-additions"
repo = "jsorrell/CarpetSkyAdditions"
entrypoint = "com.jsorrell.carpetskyadditions.SkyAdditionsExtension"
settings_manager = "com.jsorrell.carpetskyadditions.SkyAdditionsExtension.settingsManager"
settings_classes = ["com.jsorrell.carpetskyadditions.settings.SkyAdditionsSettings"]

[mods.versions."1.16"]
minecraft_version = "1.16.5"
printer_version = "v1"
entrypoint = "skyblock.SkyBlockExtension"
settings_manager = "skyblock.SkyBlockExtension.mySettingManager"
settings_classes = ["skyblock.SkyBlockSettings"]
dependencies = ["maven.modrinth:carpet:1.4.44"]
source = { host = "GitHub", tag = "2.1.4", artifact = "skyblock-1.16.5-2.1.4.jar" }

[mods.versions."1.17"]
minecraft_version = "1.17.1"
printer_version = "v1"
entrypoint = "com.jsorrell.skyblock.SkyBlockExtension"
settings_manager = "com.jsorrell.skyblock.SkyBlockExtension.settingsManager"
settings_classes = ["com.jsorrell.skyblock.SkyBlockSettings"]
dependencies = ["maven.modrinth:carpet:1.4.57"]
source = { host = "GitHub", tag = "1.17.1-3.1.0", artifact = "skyblock-1.17.1-3.1.0.jar" }

[mods.versions."1.18"]
minecraft_version = "1.18.2"
printer_version = "v1"
entrypoint = "com.jsorrell.skyblock.SkyBlockExtension"
settings_manager = "com.jsorrell.skyblock.SkyBlockExtension.settingsManager"
settings_classes = ["com.jsorrell.skyblock.SkyBlockSettings"]
dependencies = ["maven.modrinth:carpet:1.4.69"]
source = { host = "GitHub", tag = "1.18.2-3.2.4", artifact = "skyblock-1.18.2-3.2.4.jar" }

[mods.versions."1.19"]
minecraft_version = "1.19.4"
printer_version = "v3"
dependencies = [
    "maven.modrinth:carpet:1.4.101",
    "maven.modrinth:cloth-config:10.1.105+fabric",
]
source = { host = "Modrinth", version = "GDjoIpEI" }

[mods.versions."1.20"]
minecraft_version = "1.20.1"
printer_version = "v3"
dependencies = [
    "maven.modrinth:carpet:1.4.112",
    "maven.modrinth:cloth-config:11.1.106+fabric",
]
source = { host = "Modrinth", version = "2RGo6Lm4" }

[[mods]]
name = "Carpet Addons"
slug = "carpet-addons"
repo = "whoImT/carpet-addons"
settings_classes = ["carpetaddons.CarpetAddonsSettings"]

[mods.versions."1.15"]
minecraft_version = "1.15.2"
printer_version = "v1"
dependencies = ["maven.modrinth:carpet:1.4.8"]
source = { host = "GitHub", tag = "v1.0.4", artifact = "carpet-addons-1.15.2-1.0.4+v201031.jar" }

[mods.versions."1.16"]
minecraft_version = "1.16.5"
printer_version = "v1"
dependencies = ["maven.modrinth:carpet:1.4.44"]
source = { host = "GitHub", tag = "v1.0.10", artifact = "carpet-addons-1.16.5-1.0.10+v220627.jar" }

[mods.versions."1.17"]
minecraft_version = "1.17.1"
printer_version = "v1"
dependencies = ["maven.modrinth:carpet:1.4.57"]
source = { host = "GitHub", tag = "v1.0.10", artifact = "carpet-addons-1.17-1.0.10+v220627.jar" }

[mods.versions."1.18"]
minecraft_version = "1.18.2"
printer_version = "v1"
dependencies = ["maven.modrinth:carpet:1.4.69"]
source = { host = "GitHub", tag = "v1.0.10", artifact = "carpet-addons-1.18.2-1.0.10+v220627.jar" }

[[mods]]
name = "XpBeacons"
slug = "xpbeacons"
curseforge_slug = "experience-beacons-for-carpet"
project_id = 412823
settings_manager = "net.fracturedcode.xpbeacons.XpBeaconsExtension.customSettingsManager"
settings_classes = [
    "net.fracturedcode.xpbeacons.XpBeaconsSimpleSettings",
    "net.fracturedcode.xpbeacons.XpBeaconsCategorySettings.EffectSettings.HasteSettings",
    "net.fracturedcode.xpbeacons.XpBeaconsCategorySettings.EffectSettings.SpeedSettings",
    "net.fracturedcode.xpbeacons.XpBeaconsCategorySettings.EffectSettings.RegenerationSettings",
    "net.fracturedcode.xpbeacons.XpBeaconsCategorySettings.EffectSettings.ResistanceSettings",
    "net.fracturedcode.xpbeacons.XpBeaconsCategorySettings.EffectSettings.JumpBoostSettings",
    "net.fracturedcode.xpbeacons.XpBeaconsCategorySettings.EffectSettings.StrengthSettings",
    "net.fracturedcode.xpbeacons.XpBeaconsCategorySettings.BeaconSettings",
]

[mods.versions."1.16"]
minecraft_version = "1.16.5"
printer_version = "v1"
settings_manager = "xpbeacons.XpBeaconsExtension.customSettingsManager"
settings_classes = [
    "xpbeacons.XpBeaconsSimpleSettings",
    "xpbeacons.XpBeaconsCategorySettings",
]
dependencies = ["maven.modrinth:carpet:1.4.44"]
source = { host = "CurseForge", file_id = 3079300 }

[mods.versions."1.17"]
minecraft_version = "1.17.1"
printer_version = "v1"
dependencies = ["maven.modrinth:carpet:1.4.57"]
source = { host = "CurseForge", file_id = 3415043 }

[mods.versions."1.18"]
minecraft_version = "1.18.2"
printer_version = "v1"
dependencies = ["maven.modrinth:carpet:1.4.69"]
source = { host = "CurseForge", file_id = 3681671 }

[mods.versions."1.19"]
minecraft_version = "1.19.4"
printer_version = "v3"
dependencies = ["maven.modrinth:carpet:1.4.101"]
source = { host = "Modrinth", version = "7.4" }

[mods.versions."1.20"]
minecraft_version = "1.20.1"
printer_version = "v3"
dependencies = ["maven.modrinth:carpet:1.4.112"]
source = { host = "Modrinth", version = "7.4" }

[[mods]]
name = "Carpet Lunaar Addons"
slug = "lunaar-carpet-addons"
repo = "Lunaar-SMP/lunaar-carpet-addons"
entrypoint = "carpetlunaaraddons.CarpetLunaarExtension"
settings_classes = ["carpetlunaaraddons.CarpetLunaarSettings"]

[mods.versions."1.16"]
minecraft_version = "1.16.5"
printer_version = "v1"
dependencies = ["maven.modrinth:carpet:1.4.44"]
source = { host = "GitHub", tag = "v0.5.0", artifact = "carpet-lunaar-addons-1.16.5-0.5.0.jar" }

[mods.versions."1.17"]
minecraft_version = "1.17.1"
printer_version = "v1"
dependencies = ["maven.modrinth:carpet:1.4.57"]
source = { host = "GitHub", tag = "v0.5.0", artifact = "carpet-lunaar-addons-1.17.1-0.5.0.jar" }

# only supports 1.18 snapshots
# [mods.versions."1.18"]
# minecraft_version = "1.18.2"
# printer_version = "v1"
# dependencies = ["maven.modrinth:carpet:1.4.69"]
# source = { host = "GitHub", tag = "v0.5.0", artifact = "carpet-lunaar-addons-1.18_experimental-snapshot-1-0.5.0.jar" }

[[mods]]
name = "Carpet Gamerules"
slug = "carpetgamerules"
entrypoint = "de.rubixdev.carpetgamerules.CarpetGamerulesServer"
settings_manager = "de.rubixdev.carpetgamerules.CarpetGamerulesServer.settingsManager"
settings_classes = ["de.rubixdev.carpetgamerules.CarpetGamerulesSettings"]

[mods.versions."1.16"]
minecraft_version = "1.16.5"
printer_version = "v1"
dependencies = ["maven.modrinth:carpet:1.4.44"]
source = { host = "Modrinth", version = "2.0.0+1.16.5" }

[mods.versions."1.17"]
minecraft_version = "1.17.1"
printer_version = "v1"
dependencies = ["maven.modrinth:carpet:1.4.57"]
source = { host = "Modrinth", version = "2.0.0+1.17.1" }

[mods.versions."1.18"]
minecraft_version = "1.18.2"
printer_version = "v1"
dependencies = ["maven.modrinth:carpet:1.4.69"]
source = { host = "Modrinth", version = "2.0.0+1.18.2" }

[mods.versions."1.19"]
minecraft_version = "1.19.4"
printer_version = "v3"
dependencies = ["maven.modrinth:carpet:1.4.101"]
source = { host = "Modrinth", version = "2.0.0+1.19.4" }

[mods.versions."1.20"]
minecraft_version = "1.20.1"
printer_version = "v3"
dependencies = ["maven.modrinth:carpet:1.4.112"]
source = { host = "Modrinth", version = "2.0.0+1.20.1" }
