##### fabric-carpet #####
[[repos]]
host = 'github.com'
repo = 'gnembon/fabric-carpet'
printer_version = 'v1'
# entrypoint = ''
# settings_manager = ''
settings_files = ['carpet.CarpetSettings']
config_files = ['carpet.conf']
branches = [
    '1.14.4',
    '1.15.2',
    '1.16.5',
    '1.17.1',
    '1.18.2',
    '1.19.4',
    'master',
]

##### carpet-extra #####
[[repos]]
host = 'github.com'
repo = 'gnembon/carpet-extra'
printer_version = 'v1'
# entrypoint = ''
# settings_manager = ''
settings_files = ['carpetextra.CarpetExtraSettings']
config_files = ['carpet.conf']
branches = ['1.15.2', '1.16.5']

[[repos]]
host = 'github.com'
repo = 'gnembon/carpet-extra'
printer_version = 'v1'
entrypoint = 'carpetextra.CarpetExtraServer'
# settings_manager = ''
settings_files = ['carpetextra.CarpetExtraSettings']
config_files = ['carpet.conf']
branches = ['1.17.1', '1.18.2']

[[repos]]
host = 'github.com'
repo = 'gnembon/carpet-extra'
printer_version = 'v2'
entrypoint = 'carpetextra.CarpetExtraServer'
# settings_manager = ''
settings_files = ['carpetextra.CarpetExtraSettings']
config_files = ['carpet.conf']
branches = ['1.19.4', 'master']

##### carpet-autoCraftingTable #####
[[repos]]
host = 'github.com'
repo = 'gnembon/carpet-autoCraftingTable'
printer_version = 'v1'
# entrypoint = ''
# settings_manager = ''
settings_files = ['carpet_autocraftingtable.AutoCraftingTableSettings']
config_files = ['carpet.conf']
branches = ['1.15.2', '1.16.4']

[[repos]]
host = 'github.com'
repo = 'gnembon/carpet-autoCraftingTable'
printer_version = 'v2'
# entrypoint = ''
# settings_manager = ''
settings_files = ['carpet_autocraftingtable.AutoCraftingTableSettings']
config_files = ['carpet.conf']
branches = ['master']

##### carpet-fixes #####
[[repos]]
host = 'github.com'
repo = 'fxmorin/carpet-fixes'
printer_version = 'v1'
entrypoint = 'carpetfixes.CarpetFixesServer'
# settings_manager = ''
settings_files = ['carpetfixes.CarpetFixesSettings']
config_files = ['carpet.conf']
branches = ['1.16']

[[repos]]
host = 'github.com'
repo = 'fxmorin/carpet-fixes'
printer_version = 'v1'
entrypoint = 'carpetfixes.CarpetFixesServer'
settings_manager = 'carpetfixes.CarpetFixesServer.carpetFixesSettingsManager'
settings_files = ['carpetfixes.CarpetFixesSettings']
config_files = ['carpet-fixes.conf']
branches = ['1.17']

# TODO: 1.18 doesn't run
# [[repos]]
# host = 'github.com'
# repo = 'fxmorin/carpet-fixes'
# printer_version = 'v1'
# entrypoint = 'carpetfixes.CarpetFixesServer'
# settings_manager = 'carpetfixes.CarpetFixesServer.carpetFixesSettingsManager'
# settings_files = ['carpetfixes.CFSettings']
# config_files = ['carpet-fixes.conf']
# branches = ['1.18']

[[repos]]
host = 'github.com'
repo = 'fxmorin/carpet-fixes'
printer_version = 'v2'
entrypoint = 'carpetfixes.CarpetFixesServer'
settings_manager = 'carpetfixes.CarpetFixesServer.carpetFixesSettingsManager'
settings_files = ['carpetfixes.CFSettings']
config_files = ['carpet-fixes.conf']
branches = ['1.19.4', 'dev']

##### CarpetSkyAdditions #####
[[repos]]
host = 'github.com'
repo = 'jsorrell/CarpetSkyAdditions'
printer_version = 'v1'
entrypoint = 'skyblock.SkyBlockExtension'
settings_manager = 'skyblock.SkyBlockExtension.mySettingManager'
settings_files = ['skyblock.SkyBlockSettings']
config_files = ['skyblock.conf']
branches = ['1.16.5']

[[repos]]
host = 'github.com'
repo = 'jsorrell/CarpetSkyAdditions'
printer_version = 'v1'
entrypoint = 'com.jsorrell.skyblock.SkyBlockExtension'
settings_manager = 'com.jsorrell.skyblock.SkyBlockExtension.settingsManager'
settings_files = ['com.jsorrell.skyblock.SkyBlockSettings']
config_files = ['skyblock.conf']
branches = ['1.17', '1.18']

[[repos]]
host = 'github.com'
repo = 'jsorrell/CarpetSkyAdditions'
printer_version = 'v2'
entrypoint = 'com.jsorrell.carpetskyadditions.SkyAdditionsExtension'
settings_manager = 'com.jsorrell.carpetskyadditions.SkyAdditionsExtension.settingsManager'
settings_files = ['com.jsorrell.carpetskyadditions.settings.SkyAdditionsSettings']
config_files = ['carpetskyadditions.conf']
branches = ['1.19']

# TODO: uses build.gradle.kts
# [[repos]]
# host = 'github.com'
# repo = 'jsorrell/CarpetSkyAdditions'
# printer_version = 'v2'
# entrypoint = 'com.jsorrell.carpetskyadditions.SkyAdditionsExtension'
# settings_manager = 'com.jsorrell.carpetskyadditions.SkyAdditionsExtension.settingsManager'
# settings_files = ['com.jsorrell.carpetskyadditions.settings.SkyAdditionsSettings']
# config_files = ['carpetskyadditions.conf']
# branches = ['1.20']

##### carpet-addons #####
[[repos]]
host = 'github.com'
repo = 'whoImT/carpet-addons'
printer_version = 'v1'
# entrypoint = ''
# settings_manager = ''
settings_files = ['carpetaddons.CarpetAddonsSettings']
config_files = ['carpet.conf']
branches = [
    '1.15.2',
    '1.16.x',
    '1.17',
]

[[repos]]
host = 'github.com'
repo = 'whoImT/carpet-addons'
printer_version = 'v2'
# entrypoint = ''
# settings_manager = ''
settings_files = ['carpetaddons.CarpetAddonsSettings']
config_files = ['carpet.conf']
branches = ['1.19.x']

##### minitweaks #####
[[repos]]
host = 'github.com'
repo = 'manyrandomthings/minitweaks'
printer_version = 'v1'
# entrypoint = ''
# settings_manager = ''
settings_files = ['mini_tweaks.MiniTweaksSettings']
config_files = ['carpet.conf']
branches = ['1.15']

[[repos]]
host = 'github.com'
repo = 'manyrandomthings/minitweaks'
printer_version = 'v1'
entrypoint = 'minitweaks.MiniTweaks'
settings_manager = 'minitweaks.MiniTweaks.settingsManager'
settings_files = ['minitweaks.MiniTweaksSettings']
config_files = ['carpet.conf', 'minitweaks.conf']
branches = ['1.16', '1.17', '1.18']

[[repos]]
host = 'github.com'
repo = 'manyrandomthings/minitweaks'
printer_version = 'v2'
entrypoint = 'minitweaks.MiniTweaks'
settings_manager = 'minitweaks.MiniTweaksCarpetExtension.settingsManager'
settings_files = ['minitweaks.MiniTweaksSettings']
config_files = ['carpet.conf', 'minitweaks.conf']
branches = ['1.19', '1.20']

##### XpBeacons #####
[[repos]]
host = 'github.com'
repo = 'FracturedCode/XpBeacons'
printer_version = 'v2'
# entrypoint = ''
settings_manager = 'net.fracturedcode.xpbeacons.XpBeaconsExtension.customSettingsManager'
settings_files = [
    'net.fracturedcode.xpbeacons.XpBeaconsSimpleSettings',
    'net.fracturedcode.xpbeacons.XpBeaconsCategorySettings.EffectSettings.HasteSettings',
    'net.fracturedcode.xpbeacons.XpBeaconsCategorySettings.EffectSettings.SpeedSettings',
    'net.fracturedcode.xpbeacons.XpBeaconsCategorySettings.EffectSettings.RegenerationSettings',
    'net.fracturedcode.xpbeacons.XpBeaconsCategorySettings.EffectSettings.ResistanceSettings',
    'net.fracturedcode.xpbeacons.XpBeaconsCategorySettings.EffectSettings.JumpBoostSettings',
    'net.fracturedcode.xpbeacons.XpBeaconsCategorySettings.EffectSettings.StrengthSettings',
    'net.fracturedcode.xpbeacons.XpBeaconsCategorySettings.BeaconSettings',
]
config_files = ['carpet.conf', 'xpbeacons.conf']
branches = ['master']

##### lunaar-carpet-addons #####
[[repos]]
host = 'github.com'
repo = 'Lunaar-SMP/lunaar-carpet-addons'
printer_version = 'v1'
entrypoint = 'carpetlunaaraddons.CarpetLunaarExtension'
# settings_manager = ''
settings_files = ['carpetlunaaraddons.CarpetLunaarSettings']
config_files = ['carpet.conf']
branches = ['1.16']

[[repos]]
host = 'github.com'
repo = 'Lunaar-SMP/lunaar-carpet-addons'
printer_version = 'v1'
entrypoint = 'carpetlunaaraddons.CarpetLunaarExtension'
# settings_manager = ''
settings_files = ['carpetlunaaraddons.CarpetLunaarSettings']
config_files = ['carpet.conf']
branches = ['1.17']
mappings_override = '1.17.1+build.65'

[[repos]]
host = 'github.com'
repo = 'Lunaar-SMP/lunaar-carpet-addons'
printer_version = 'v1'
entrypoint = 'carpetlunaaraddons.CarpetLunaarExtension'
# settings_manager = ''
settings_files = ['carpetlunaaraddons.CarpetLunaarSettings']
config_files = ['carpet.conf']
branches = ['1.18']
mappings_override = '21w44a+build.10'

##### Rug #####
[[repos]]
host = 'github.com'
repo = 'RubixDev/Rug'
printer_version = 'v1'
entrypoint = 'de.rubixdev.rug.RugServer'
# settings_manager = ''
settings_files = ['de.rubixdev.rug.RugSettings']
config_files = ['carpet.conf']
branches = ['1.16', '1.17', '1.18']

[[repos]]
host = 'github.com'
repo = 'RubixDev/Rug'
printer_version = 'v2'
entrypoint = 'de.rubixdev.rug.RugServer'
# settings_manager = ''
settings_files = ['de.rubixdev.rug.RugSettings']
config_files = ['carpet.conf']
# TODO: 1.20 is broken :(
branches = ['1.19']
