name: Update database
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'
jobs:
  run-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Cache
        uses: actions/cache@v3
        with:
          path: ./cache
          key: "${{ runner.os }}-${{ hashFiles('./data/*.json') }}"
          restore-keys: ${{ runner.os }}-

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Update repos.json
        run: python update_repos_json.py

      - name: Run with Java 18
        run: ./run_one.sh 18
        continue-on-error: true

      - name: Run with Java 16
        run: ./run_one.sh 16
        continue-on-error: true

      - name: Run with Java 8
        run: ./run_one.sh 8
        continue-on-error: true

      - name: Combine output
        run: python combine.py

      - name: Capture date
        id: capture-date
        run: echo "::set-output name=date::$(date -u)"

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          add: data
          author_name: github-actions[bot]
          default_author: github_actions
          message: "Update database '${{ steps.capture-date.outputs.date }}'"
