name: Update database
on:
  push:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 0 * * 0'
jobs:
  run-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Restore Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Run
        uses: actions-rs/cargo@v1
        with:
          command: run

      - name: Capture date
        id: capture-date
        run: echo "date=$(date -u)" >> "$GITHUB_OUTPUT"

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          add: data
          committer_name: github-actions[bot]
          committer_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: "Update database '${{ steps.capture-date.outputs.date }}'"
